
runtime: python27
api_version: 1
threadsafe: yes

# [START handlers]
handlers:
# - url: /
#   static_files: templates/index/index.html
#   upload: templates/index/index\.html


- url: /static
  static_dir: static

- url: /.*
  script: main.app
  secure: always
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: MySQLdb
  version: latest
# [END libraries]

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: 
    CLOUDSQL_USER: 
    CLOUDSQL_PASSWORD:
    CLOUDSQL_DATABASE: 
# [END env_variables]
